function getTime(){return Date.now()}function Y(a){return EngineInstance.windowRect.height-a}function world(a){var b=math.v2.create(a);b[1]=Y(a[1]);math.v2.multScalarMutate(b,1/EngineInstance.ppm);return b}function window(a){a=math.v2.create(a);math.v2.multScalarMutate(a,EngineInstance.ppm);a[1]=Y(a[1]);return a}function windowVector(a){var b=math.v2.create(a);b[1]=-a[1];math.v2.multScalarMutate(b,EngineInstance.ppm);return b}
var constants={PARTICLE_COLOR:"lightblue",PARTICLE_STRING_COLOR:"black",PARTICLE_WIDTH:3,RIGID_BODY_COLOR:"lightblue",RIGID_BODY_STRING_COLOR:"black",RIGID_BODY_WIDTH:3,GRAVITY_COLOR:"orange",WIND_COLOR:"orange",DRAG_COLOR:"lightblue",SPRING_COLOR:"lightgreen",ANCHORED_SPRING_COLOR:"darkgreen",BUNGEE_COLOR:"pink",ANCHORED_BUNGEE_COLOR:"magenta",AERO_COLOR:"purple",CABLE_COLOR:"grey",ANCHORED_CABLE_COLOR:"#333333",ROD_COLOR:"black",ANCHORED_ROD_COLOR:"#333333",COLLISION_DETECTION_COLOR:"purple",COLLISION_BOX_COLOR:"purple",
COLLISION_BOX_TOL_COLOR:"pink",EARTH_GRAVITATIONAL_CONSTANT:-9.81,DEFAULT_GRAVITATIONAL_CONSTANT:-9.81,DEFAULT_DRAG_VELOCITY_COEFF:0.5,DEFAULT_DRAG_VELOCITY_SQUARED_COEFF:0.05,DEFAULT_COLLISION_RESTITUTION:0.5,TWO_PI:Math.PI*2};function Resources(){}Resources.configuration={ROOT_PATH:"../",IMG_PATH:"../img/"};Resources.loadImage=function(a){var b=new Image;b.src=Resources.configuration.IMG_PATH+a;return b};function Observable(){this.listeners={};this.addEventListener=function(a,b){typeof this.listeners[a]=="undefined"&&(this.listeners[a]=[]);return this.listeners[a].push(b)};this.dispatchEvent=function(a,b){if(typeof this.listeners[a]!="undefined")for(var c=this.listeners[a].length;c--;)this.listeners[a][c].call(this,b)};this.removeEventListener=function(a,b){if(this.listeners[a]instanceof Array)for(var c=this.listeners[a],d=0,e=c.length;d<e;d++)if(c[d]===b)return c.splice(d,1)}}
function bind(a,b,c,d,e,g,f){var h=d[e];f!=void 0&&(h=f(h));b[c]=h;d.addEventListener(a,function(g){EngineInstance.debug&&EngineInstance.verbose&&console.debug("%s event type, %o event, setting target %o.%s to source %o.%s",a,g,b,c,d,e);g=d[e];f!=void 0&&(g=f(g));b[c]=g});g&&bind(a,d,e,b,c,!1)};function Queue(){var a=[];this.getSize=function(){return a.length};this.isEmpty=function(){return a.length==0};this.enqueue=function(b){return a.push(b)};this.dequeue=function(){return a.shift()};this.getElements=function(){return a}}
function RingBuffer(a){if(typeof a=="undefined")throw Error("Valid integer size expected");var b=new Queue;this.getSize=function(){return b.getSize()};this.isEmpty=function(){return b.isEmpty()};this.enqueue=function(c){this.getSize()>=a&&b.dequeue();return b.enqueue(c)};this.dequeue=function(){return b.dequeue()};this.getElements=function(){return b.getElements()}};Rectangle=function(a,b,c,d){this.x=a||0;this.y=b||0;this.width=c||0;this.height=d||0;this.draw=function(){ctx.strokeRect(this.x,this.y,this.width,this.height)};this.isPointInside=function(a){if(a[0]>=this.x&&a[0]<=this.x+this.width&&a[1]>=this.y&&a[1]<=this.y+this.height)return!0;return!1};this.isPointInsideStrict=function(a){if(a[0]>this.x&&a[0]<this.x+this.width&&a[1]>this.y&&a[1]<this.y+this.height)return!0;return!1};this.shrink=function(a){var b=this.clone();b.shrinkMutate(a);return b};this.shrinkMutate=
function(a){this.x+=a;this.y+=a;this.width-=a*2;this.height-=a*2};this.clone=function(){return new Rectangle(this.x,this.y,this.width,this.height)};this.toString=function(){return"(x="+this.x+", y="+this.y+", w="+this.width+", h="+this.height+")"}};
Vector2=function(a,b){this.x=a||0;this.y=b||0;this.add=function(a){var b=this.clone();b.x+=a.x;b.y+=a.y;return b};this.addMutate=function(a){this.x+=a.x;this.y+=a.y};this.sub=function(a){var b=this.clone();b.x-=a.x;b.y-=a.y;return b};this.subMutate=function(a){this.x-=a.x;this.y-=a.y};this.inverse=function(){return new Vector2(-this.x,-this.y)};this.inverseMutate=function(){this.x=-this.x;this.y=-this.y};this.multScalar=function(a){var b=this.clone();b.x*=a;b.y*=a;return b};this.multScalarMutate=
function(a){this.x*=a;this.y*=a};this.dotProduct=function(a){return this.x*a.x+this.y*a.y};this.vectorProduct=function(a){return this.x*a.y-this.y*a.x};this.getMagnitude=function(){return Math.sqrt(this.getMagnitudeSquare())};this.getMagnitudeSquare=function(){return this.x*this.x+this.y*this.y};this.normalize=function(){var a=this.clone();a.normalizeMutate();return a};this.normalizeMutate=function(){var a=this.getMagnitude();a>0&&this.multScalarMutate(1/a)};this.zeroMutate=function(){this.y=this.x=
0};this.clone=function(){return new Vector2(this.x,this.y)};this.equals=function(a){if(this===a)return!0;return this.x==a.x&&this.y==a.y};this.toString=function(){return"("+this.x+", "+this.y+")"};this.draw=function(a){ctx.save();ctx.strokeStyle=a==void 0?"lightblue":a;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(this.x,this.y);ctx.stroke();ctx.restore()};this.drawPoint=function(a){ctx.save();ctx.fillStyle=a==void 0?"magenta":a;ctx.translate(this.x,this.y);ctx.fillRect(-1,-1,2,2);ctx.restore()}};
Vector2.getAngle=function(a,b){return Math.acos(a.normalize().dotProduct(b.normalize()))};Vector2.getDistance=function(a,b){return a.sub(b).getMagnitude()};Vector2.getDistanceSquare=function(a,b){return a.sub(b).getMagnitudeSquare()};Vector2.isWithin=function(a,b,c){return Vector2.getDistanceSquare(a,b)<=c*c};Vector2.isWithinStrict=function(a,b,c){return Vector2.getDistanceSquare(a,b)<c*c};
Vector3=function(a,b,c){this.x=a||0;this.y=b||0;this.z=c||0;this.add=function(a){var b=this.clone();b.x+=a.x;b.y+=a.y;b.z+=a.z;return b};this.addMutate=function(a){this.x+=a.x;this.y+=a.y;this.z+=a.z};this.sub=function(a){var b=this.clone();b.x-=a.x;b.y-=a.y;b.z-=a.z;return b};this.subMutate=function(a){this.x-=a.x;this.y-=a.y;this.z-=a.z};this.reverse=function(){return new Vector3(-this.x,-this.y,-this.z)};this.multScalar=function(a){var b=this.clone();b.x*=a;b.y*=a;b.z*=a;return b};this.multScalarMutate=
function(a){this.x*=a;this.y*=a;this.z*=a};this.dotProduct=function(a){return this.x*a.x+this.y*a.y+this.z*a.z};this.getMagnitude=function(){return Math.sqrt(this.getMagnitudeSquare())};this.getMagnitudeSquare=function(){return this.x*this.x+this.y*this.y+this.z*this.z};this.normalize=function(){var a=this.clone();a.normalizeMutate();return a};this.normalizeMutate=function(){var a=this.getMagnitude();a>0&&this.multScalarMutate(1/a)};this.zeroMutate=function(){this.z=this.y=this.x=0};this.clone=function(){return new Vector3(this.x,
this.y,this.z)};this.toString=function(){return"("+this.x+", "+this.y+","+this.z+")"}};
Matrix2=function(a,b,c,d){this.e=[a||0,b||0,c||0,d||0];this.det=0;this.inverse=void 0;this.recaclulateDeterminant=function(){this.det=this.e[0]*this.e[3]-this.e[1]*this.e[2]};this.recaclulateDeterminant();this.recaclulateInverse=function(){if(this.det!=0){var a=1/this.det,a=new Matrix2(a*this.e[3],-a*this.e[1],-a*this.e[2],a*this.e[0]);a.inverse=this.clone();this.inverse=a}};this.multVector=function(a){return new Vector2(a.x*this.e[0]+a.y*this.e[1],a.x*this.e[2]+a.y*this.e[3])};this.multVectorMutate=
function(a){a.x=a.x*this.e[0]+a.y*this.e[1];a.y=a.x*this.e[2]+a.y*this.e[3]};this.mult=function(a){return new Matrix2(this.e[0]*a.e[0]+this.e[1]*a.e[2],this.e[0]*a.e[1]+this.e[1]*a.e[3],this.e[2]*a.e[0]+this.e[3]*a.e[2],this.e[2]*a.e[1]+this.e[3]*a.e[3])};this.add=function(a){return new Matrix2(this.e[0]+a.e[0],this.e[1]+a.e[1],this.e[2]+a.e[2],this.e[3]+a.e[3])};this.addMutate=function(a){this.e[0]+=a.e[0];this.e[1]+=a.e[1];this.e[2]+=a.e[2];this.e[3]+=a.e[3]};this.getEntry=function(a,b){return this.e[a*
2+b]};this.getDeterminant=function(){return this.det};this.isSingular=function(){return this.det==0};this.isInvertable=function(){return this.det!=0};this.getInverse=function(){!this.inverse&&this.isInvertable()&&this.recaclulateInverse();return this.inverse};this.equals=function(a){if(this===a)return!0;if(this.e.length!=a.e.length)return!1;for(i in this.e)if(this.e[i]!=a.e[i])return!1;return!0};this.clone=function(){return new Matrix2(this.e[0],this.e[1],this.e[2],this.e[3])}};
Identity2=function(){Matrix2.call(this,1,0,0,1)};Identity2.prototype=new Matrix2;Identity2.instance=new Identity2;RotationMatrix2=function(a){Matrix2.call(this,Math.cos(a),-Math.sin(a),Math.sin(a),Math.cos(a))};RotationMatrix2.prototype=new Matrix2;
Matrix3=function(a,b,c,d,e,g,f,h,k){this.e=[a||0,b||0,c||0,d||0,e||0,g||0,f||0,h||0,k||0];this.det=0;this.inverse=void 0;this.recaclulateDeterminant=function(){this.det=this.e[0]*this.e[4]*this.e[8]+this.e[1]*this.e[5]*this.e[6]+this.e[2]*this.e[3]*this.e[7]-this.e[0]*this.e[5]*this.e[7]-this.e[1]*this.e[3]*this.e[8]-this.e[2]*this.e[4]*this.e[6]};this.recaclulateDeterminant();this.recaclulateInverse=function(){if(this.det!=0){var a=1/this.det,a=new Matrix3(a*(this.e[4]*this.e[8]-this.e[7]*this.e[5]),
a*(this.e[6]*this.e[5]-this.e[3]*this.e[8]),a*(this.e[3]*this.e[7]-this.e[6]*this.e[4]),a*(this.e[7]*this.e[2]-this.e[1]*this.e[8]),a*(this.e[0]*this.e[8]-this.e[6]*this.e[2]),a*(this.e[6]*this.e[1]-this.e[0]*this.e[7]),a*(this.e[1]*this.e[5]-this.e[4]*this.e[2]),a*(this.e[3]*this.e[2]-this.e[0]*this.e[5]),a*(this.e[0]*this.e[4]-this.e[3]*this.e[1]));a.inverse=this.clone();this.inverse=a}};this.multVector=function(a){return new Vector3(a.x*this.e[0]+a.y*this.e[1]+a.z*this.e[2],a.x*this.e[3]+a.y*this.e[4]+
a.z*this.e[5],a.x*this.e[6]+a.y*this.e[7]+a.z*this.e[8])};this.multVectorMutate=function(a){a.x=a.x*this.e[0]+a.y*this.e[1]+a.z*this.e[2];a.y=a.x*this.e[3]+a.y*this.e[4]+a.z*this.e[5];a.z=a.x*this.e[6]+a.y*this.e[7]+a.z*this.e[8]};this.mult=function(a){return new Matrix3(this.e[0]*a.e[0]+this.e[1]*a.e[3]+this.e[2]*a.e[6],this.e[0]*a.e[1]+this.e[1]*a.e[4]+this.e[2]*a.e[7],this.e[0]*a.e[2]+this.e[1]*a.e[5]+this.e[2]*a.e[8],this.e[3]*a.e[0]+this.e[4]*a.e[3]+this.e[5]*a.e[6],this.e[3]*a.e[1]+this.e[4]*
a.e[4]+this.e[5]*a.e[7],this.e[3]*a.e[2]+this.e[4]*a.e[5]+this.e[5]*a.e[8],this.e[6]*a.e[0]+this.e[7]*a.e[3]+this.e[8]*a.e[6],this.e[6]*a.e[1]+this.e[7]*a.e[4]+this.e[8]*a.e[7],this.e[6]*a.e[2]+this.e[7]*a.e[5]+this.e[8]*a.e[8])};this.add=function(a){return new Matrix2(this.e[0]+a.e[0],this.e[1]+a.e[1],this.e[2]+a.e[2],this.e[3]+a.e[3],this.e[4]+a.e[4],this.e[5]+a.e[5],this.e[6]+a.e[6],this.e[7]+a.e[7],this.e[8]+a.e[8])};this.addMutate=function(a){this.e[0]+=a.e[0];this.e[1]+=a.e[1];this.e[2]+=a.e[2];
this.e[3]+=a.e[3];this.e[4]+=a.e[4];this.e[5]+=a.e[5];this.e[6]+=a.e[6];this.e[7]+=a.e[7];this.e[8]+=a.e[8]};this.getEntry=function(a,b){return this.e[a*2+b]};this.getDeterminant=function(){return this.det};this.isSingular=function(){return this.det==0};this.isInvertable=function(){return this.det!=0};this.getInverse=function(){!this.inverse&&this.isInvertable()&&this.recaclulateInverse();return this.inverse};this.equals=function(a){if(this===a)return!0;if(this.e.length!=a.e.length)return!1;for(i in this.e)if(this.e[i]!=
a.e[i])return!1;return!0};this.clone=function(){return new Matrix3(this.e[0],this.e[1],this.e[2],this.e[3],this.e[4],this.e[5],this.e[6],this.e[7],this.e[8])}};TransformationMatrix3=function(a,b,c){Matrix3.call(this,Math.cos(a),-Math.sin(a),b,Math.sin(a),Math.cos(a),c,0,0,1)};TransformationMatrix3.prototype=new Matrix3;var math={};
math.v2={create:function(a){return a?[a[0],a[1]]:[0,0]},add:function(a,b){return[a[0]+b[0],a[1]+b[1]]},addMutate:function(a,b){a[0]+=b[0];a[1]+=b[1]},sub:function(a,b){return[a[0]-b[0],a[1]-b[1]]},subMutate:function(a,b){a[0]-=b[0];a[1]-=b[1]},inverse:function(a){return[-a[0],-a[1]]},inverseMutate:function(a){a[0]=-a[0];a[1]=-a[1]},multScalar:function(a,b){return[a[0]*b,a[1]*b]},multScalarMutate:function(a,b){a[0]*=b;a[1]*=b},dotProduct:function(a,b){return a[0]*b[0]+a[1]*b[1]},vectorProduct:function(a,b){return a[0]*
b[1]-a[1]*b[0]},getMagnitude:function(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1])},getMagnitudeSquare:function(a){return a[0]*a[0]+a[1]*a[1]},normalize:function(a){a=math.v2.create(a);math.v2.normalizeMutate(a);return a},normalizeMutate:function(a){var b=math.v2.getMagnitude(a);b>0&&math.v2.multScalarMutate(a,1/b)},zeroMutate:function(a){a[0]=0;a[1]=0},getAngle:function(a,b){return Math.acos(math.v2.dotProduct(math.v2.normalize(a),math.v2.normalize(b)))},getDistance:function(a,b){return math.v2.getMagnitude(math.v2.sub(a,
b))},getDistanceSquare:function(a,b){return math.v2.getMagnitudeSquare(math.v2.sub(a,b))},isWithin:function(a,b,c){return math.v2.getDistanceSquare(a,b)<=c*c},isWithinStrict:function(a,b,c){return math.v2.getDistanceSquare(a,b)<c*c}};
math.v3={create:function(a){return a?[a[0],a[1],a[2]]:[0,0,0]},add:function(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2]]},addMutate:function(a,b){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2]},sub:function(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]]},subMutate:function(a,b){a[0]-=b[0];a[1]-=b[1];a[2]-=b[2]},inverse:function(a){return[-a[0],-a[1],-a[2]]},inverseMutate:function(a){a[0]=-a[0];a[1]=-a[1];a[2]=-a[2]},multScalar:function(a,b){return[a[0]*b,a[1]*b,a[2]*b]},multScalarMutate:function(a,b){a[0]*=b;a[1]*=b;
a[2]*=b},dotProduct:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},vectorProduct:function(a,b){return a[0]*b[1]-a[1]*b[0]},getMagnitude:function(a){return Math.sqrt(math.v2.getMagnitudeSquare(a))},getMagnitudeSquare:function(a){return a[0]*a[0]+a[1]*a[1]+a[2]*a[2]},normalize:function(a){a=math.v2.create(a);math.v2.normalizeMutate(a);return a},normalizeMutate:function(a){var b=math.v2.getMagnitude(a);b>0&&math.v2.multScalarMutate(a,1/b)},zeroMutate:function(a){a[0]=0;a[1]=0;a[2]=0},getAngle:function(a,
b){return Math.acos(math.v2.dotProduct(math.v2.normalize(a),math.v2.normalize(b)))},getDistance:function(a,b){return math.v2.getMagnitude(math.v2.sub(a,b))},getDistanceSquare:function(a,b){return math.v2.getMagnitudeSquare(math.v2.sub(a,b))},isWithin:function(a,b,c){return math.v2.getDistanceSquare(a,b)<=c*c},isWithinStrict:function(a,b,c){return math.v2.getDistanceSquare(a,b)<c*c}};
math.m2={create:function(a){return a?[a[0],a[1],a[2],a[3]]:[0,0,0,0]},createIdentity:function(){return[1,0,0,1]},createRotation:function(a){return[Math.cos(a),-Math.sin(a),Math.sin(a),Math.cos(a)]},getDeterminant:function(a){return a[0]*a[3]-a[1]*a[2]},isInvertable:function(a){return math.v2.getDeterminant(a)!=0},isSingular:function(a){return math.v2.getDeterminant(a)==0},getInverse:function(a){var b=math.v2.getDeterminant(a);if(b!=0)return b=1/b,[b*a[3],-b*a[1],-b*a[2],b*a[0]]},multVector:function(a,
b){return[b[0]*a[0]+b[1]*a[1],b[0]*a[2]+b[1]*a[3]]},multVectorMutate:function(a,b){b[0]=b[0]*a[0]+b[1]*a[1];b[1]=b[0]*a[2]+b[1]*a[3]},mult:function(a,b){return[a[0]*b[0]+a[1]*b[2],a[0]*b[1]+a[1]*b[3],a[2]*b[0]+a[3]*b[2],a[2]*b[1]+a[3]*b[3]]},add:function(a,b){return[a[0]+b[0],a[1]+b[1],a[2]+b[2],a[3]+b[3]]},addMutate:function(a,b){a[0]+=b[0];a[1]+=b[1];a[2]+=b[2];a[3]+=b[3]},getEntry:function(a,b,c){return a[b*2+c]},equals:function(a,b){return a[0]==b[0]&&a[1]==b[1]&&a[2]==b[2]&&a[3]==b[3]}};function Engine(){Observable.call(this);this.onreset=void 0;this.reset=function(){if(this.onreset)this.onreset();this.dispatchEvent("reset",void 0)};this.oninit=void 0;this.init=function(){if(this.oninit)this.oninit();this.dispatchEvent("init",void 0)};this.onmousemove=void 0;this.mousemove=function(a){if(this.onmousemove)this.onmousemove(a);this.dispatchEvent("mousemove",a)};this.onmousedown=void 0;this.mousedown=function(a){if(this.onmousedown)this.onmousedown(a);this.dispatchEvent("mousedown",
a)};this.onmouseup=void 0;this.mouseup=function(a){if(this.onmouseup)this.onmouseup(a);this.dispatchEvent("mouseup",a)};this.onmouseover=void 0;this.mouseover=function(a){if(this.onmouseover)this.onmouseover(a);this.dispatchEvent("mouseover",a)};this.onmouseout=void 0;this.mouseout=function(a){if(this.onmouseout)this.onmouseout(a);this.dispatchEvent("mouseout",a)};this.onmousewheel=void 0;this.mousewheel=function(a){if(this.onmousewheel)this.onmousewheel(a);this.dispatchEvent("mousewheel",a)};this.onkeydown=
void 0;this.keydown=function(a){if(this.onkeydown)this.onkeydown(a);this.dispatchEvent("keydown",a)};this.onkeyup=void 0;this.keyup=function(a){if(this.onkeyup)this.onkeyup(a);this.dispatchEvent("keyup",a)};this.onpause=void 0;this.pause=function(){if(this.onpause)this.onpause();this.dispatchEvent("pause",void 0)};this.targetFps=30;this.debug=!0;this.verbose=!1;this.ctx=this.windowRect=this.canvas=null;this.avgFps=this.lastFrame=this.fps=0;this.lastFPS=getTime();this.lastSync=getTime();this.paused=
this.running=!1;this.ppm=1;this.engineInit=function(){this.debug&&console.debug("Start. Initializing");this.canvas=document.getElementById("canvas");if(this.canvas.getContext){this.ctx=this.canvas.getContext("2d");this.debug&&console.debug("Found 2d context");this.windowRect=new Rectangle(0,0,this.canvas.width,this.canvas.height);this.canvas.onmousemove=function(a){EngineInstance.mousemove(a)};this.canvas.onmousedown=function(a){EngineInstance.mousedown(a)};this.canvas.onmouseup=function(a){EngineInstance.mouseup(a)};
this.canvas.onmouseover=function(a){EngineInstance.mouseover(a)};this.canvas.onmouseout=function(a){EngineInstance.mouseout(a)};this.canvas.onmousewheel=function(a){EngineInstance.mousewheel(a)};var a=this.ctx.createLinearGradient(0,-75,0,75);a.addColorStop(0,"#232256");a.addColorStop(1,"#143778");this.initGame();this.init()}else throw Error("Canvas not supported");this.debug&&console.debug("Done. Initializing");document.onkeydown=function(a){if(a.keyCode==68)EngineInstance.debug=!EngineInstance.debug,
console.debug("Debug enabled: "+EngineInstance.debug);EngineInstance.keydown(a)};document.onkeyup=function(a){EngineInstance.keyup(a)}};this.engineReset=function(){this.lastFrame=this.fps=0;this.lastFPS=getTime();this.lastSync=getTime();this.reset()};this.getDelta=function(){var a=getTime(),b=a-this.lastFrame;this.lastFrame=a;return b};this.updateFPS=function(){if(getTime()-this.lastFPS>1E3)this.avgFps=this.fps,this.fps=0,this.lastFPS+=1E3;this.fps++};this.engineStart=function(){this.engineReset();
this.getDelta();this.running?console.warn("Start called, but already running"):(this.running=!0,this.startGame(),this.engineMain())};this.enginePause=function(){this.paused=!0;this.pause()};this.engineContinue=function(){this.paused=!1;this.pause();this.engineReset();setTimeout(EngineInstance.engineMain,0)};this.engineStop=function(){this.running?(this.running=!1,this.stopGame()):console.warn("Stop called, but not running")};this.engineSync=function(){var a=this.lastSync+1E3/this.targetFps-getTime();
setTimeout(EngineInstance.engineMain,a);this.lastSync+=1E3/this.targetFps};this.engineMain=function(){var a=EngineInstance;if(a.running&&!a.paused){var b=a.getDelta();a.updateGame(b);a.ctx.save();a.renderGame(this.ctx);a.ctx.restore();a.updateFPS();a.engineSync()}};this.initGame=function(){};this.startGame=function(){};this.updateGame=function(){};this.renderGame=function(){};this.stopGame=function(){var a=this.ctx,b=this.canvas,c=this.windowRect;a.save();a.globalAlpha=0.3;a.fillStyle="black";a.fillRect(0,
0,b.width,b.height);a.globalAlpha=1;a.fillStyle="white";a.fillText("Stopped",(c.width-a.measureText("Stopped").width)/2,c.height/2);a.restore()}}Engine.prototype=new Observable;var EngineInstance=void 0;function BoundaryAction(){this.update=function(){}}function BoundaryBounce(){this.update=function(a){var b=a.boundingBox;if(a.pos.x<b.x)a.pos.x=b.x,a.vel.x=-a.vel.x;if(a.pos.x+a.width>b.x+b.width)a.pos.x=b.x+b.width-a.width,a.vel.x=-a.vel.x;if(a.pos.y<b.y)a.pos.y=b.y,a.vel.y=-a.vel.y;if(a.pos.y+a.height>b.y+b.height)a.pos.y=b.y+b.height-a.height,a.vel.y=-a.vel.y}}BoundaryBounce.prototype=new BoundaryAction;BoundaryBounce.instance=new BoundaryBounce;
function BoundaryWrap(){this.update=function(a){var b=a.boundingBox;if(a.pos.x+a.width<b.x)a.pos.x=b.x+b.width;if(a.pos.x>b.x+b.width)a.pos.x=b.x-a.width;if(a.pos.y+a.height<b.y)a.pos.y=b.y+b.height;if(a.pos.y>b.y+b.height)a.pos.y=b.y-a.height}}BoundaryWrap.prototype=new BoundaryAction;BoundaryWrap.instance=new BoundaryWrap;function BoundaryDie(){this.update=function(a){var b=a.boundingBox;if(a.pos.x<b.x||a.pos.x+a.width>b.x+b.width||a.pos.y<b.y||a.pos.y+a.height>b.y+b.height)a.alive=!1}}
BoundaryDie.prototype=new BoundaryAction;BoundaryDie.instance=new BoundaryDie;function Sprite(){this.image=Resources.loadImage(name);this.height=this.width=0;this.draw=function(){ctx.drawImage(this.image,0,0)}}
function Entity(a){this.alive=!0;this.height=this.width=16;this.pos=new Vector2;this.vel=new Vector2;this.boundingBox=windowRect;this.boundingCollisionAction=BoundaryBounce.instance;this.angle=0;this.anglev=Math.PI/1;this.sprite=void 0;if(a)this.sprite=a,this.width=a.width,this.height=a.height;this.getX=function(){return this.pos.x};this.getY=function(){return this.pos.y};this.update=function(a){a/=1E3;this.angle+=this.anglev*a;this.pos.x+=this.vel.x*a;this.pos.y+=this.vel.y*a;this.boundingCollisionAction.update(this)};
this.drawPlaceholder=function(){ctx.strokeRect(0,0,this.width,this.height);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(this.width,this.height);ctx.moveTo(this.width,0);ctx.lineTo(0,this.height);ctx.stroke()};this.draw=function(){ctx.save();ctx.translate(this.pos.x,this.pos.y);ctx.rotate(this.angle);this.sprite?this.sprite.draw():this.drawPlaceholder();ctx.restore()}}
function EntityManager(){this.entities=[];this.addEntity=function(a){debug&&console.debug("Adding new managed entity");return this.entities.push(a)};this.removeEntityAtIndex=function(a){debug&&console.debug("Removing managed entity");return this.entities.splice(a,1)};this.update=function(a){for(i in this.entities){var b=this.entities[i];b.update(a);b.alive||this.removeEntityAtIndex(i)}};this.draw=function(){for(i in this.entities)this.entities[i].draw()}};function Background(){this.update=function(){};this.draw=function(){}}function FillBackground(a){this.fillStyle=a;this.draw=function(a,c){a.fillStyle=this.fillStyle;a.fillRect(c.x,c.y,c.width,c.height)}}FillBackground.prototype=new Background;
function StarryBackground(a,b){this.cartoonify=!0;this.fillStyle=b||"darkblue";this.numStars=a||50;this.shootingStar=void 0;this.stars=[];for(var c=a;c--;)this.stars.push(new Star(EngineInstance.windowRect.width*Math.random(),EngineInstance.windowRect.height*Math.random(),Math.random()));this.update=function(b){var e=b/1E3;if(this.shootingStar){if(this.shootingStar.x+=500*e,this.shootingStar.y+=300*e,this.shootingStar.x>EngineInstance.windowRect.width)this.shootingStar=void 0}else if(Math.random()<
0.0020)this.shootingStar=new Star(0,Math.random()*EngineInstance.windowRect.height,Math.random());for(c=0;c<a;c++)this.stars[c].animate(b)};this.draw=function(b,e){b.save();b.fillStyle=this.fillStyle;b.fillRect(e.x,e.y,e.width,e.height);for(c=0;c<a;c++){var g=this.stars[c];this.cartoonify?g.drawCartoon(b):g.draw(b)}this.shootingStar&&(this.cartoonify?this.shootingStar.drawCartoon(b):this.shootingStar.draw(b));b.restore()}}StarryBackground.prototype=new Background;
function Star(a,b,c){this.x=a;this.y=b;this.i=c;this.r=Math.floor(Math.random()*4)+2;this.animate=function(){if(Math.random()<0.0050)this.i=Math.random()};this.draw=function(a){a.fillStyle="rgba(255, 255, 255, "+this.i+")";a.fillRect(this.x,this.y,1,1)};this.drawCartoon=function(a){a.save();a.fillStyle="rgba(255, 255, 255, "+this.i+")";a.translate(this.x,this.y);a.beginPath();a.moveTo(this.r,0);for(var b=0;b<9;b++)a.rotate(Math.PI/5),b%2==0?a.lineTo(this.r/0.525731*0.200811,0):a.lineTo(this.r,0);
a.closePath();a.fill();a.restore()}};function FancyMouse(){var a=new RingBuffer(10);EngineInstance.addEventListener("mousemove",function(b){a.enqueue([b.offsetX,b.offsetY])});this.lastDelta=0;this.update=function(b){this.lastDelta+=b;if(this.lastDelta>100/a.getElements().length)a.dequeue(),this.lastDelta=0};this.draw=function(b){b.save();b.beginPath();for(var c=a.getElements(),d=c.length;d--;)d>1&&(b.moveTo(c[d-1][0],c[d-1][1]),b.lineTo(c[d][0],c[d][1]),b.fillRect(c[d][0]-d,c[d][1]-d,d*2,d*2));b.stroke();b.restore()}};function Particle(a){Observable.call(this);this.uid=Particle.getNextUid();this.pos=math.v2.create();this.vel=math.v2.create();this.acc=math.v2.create();this.damping=1;this.inverseMass=0;if(a)this.inverseMass=1/a;this.forceAccum=math.v2.create();this.isCloseToPoint=function(a,c){return math.v2.isWithin(this.pos,a,c)};this.hasFiniteMass=function(){return this.inverseMass>0};this.applyForce=function(a){math.v2.addMutate(this.forceAccum,a)};this.clearForceAccum=function(){math.v2.zeroMutate(this.forceAccum)};
this.setInverseMass=function(a){this.inverseMass=a};this.setMass=function(a){this.inverseMass=a==0?0:1/a};this.getMass=function(){return this.inverseMass==0?0:1/this.inverseMass};this.integrate=function(a){a/=1E3;math.v2.addMutate(this.pos,math.v2.multScalar(this.vel,a));var c=math.v2.add(this.acc,math.v2.multScalar(this.forceAccum,this.inverseMass));math.v2.addMutate(this.vel,math.v2.multScalar(c,a));math.v2.multScalarMutate(this.vel,Math.pow(this.damping,a));this.clearForceAccum()};this.ondie=void 0;
this.die=function(){if(this.ondie)this.ondie();this.dispatchEvent("die")};this.accept=function(a){a.visitParticle(this)};this.toString=function(){return"uid="+this.uid}}Particle.prototype=new Observable;Particle.nextUid=0;Particle.getNextUid=function(){return Particle.nextUid++};
function ParticleForceRegistry(){this.entries=[];this.add=function(a,b){for(var c,d=!1,e=this.entries.length;e--;)if(c=this.entries[e],c.particle===a){d=!0;break}d?c.forceGenerators.push(b):(c={particle:a,forceGenerators:Array(b)},this.entries.push(c))};this.getForceGenerators=function(a){for(var b=this.entries.length;b--;){var c=this.entries[b];if(c.particle===a)return c.forceGenerators}};this.removeForceGenerators=function(a){for(var b=this.entries.length;b--;)this.entries[b].particle===a&&this.entries.splice(b,
1)};this.removeForceGenerator=function(a){for(var b=this.entries.length;b--;)for(var c=this.entries[b],d=c.forceGenerators.length;d--;)c.forceGenerators[d]===a&&c.forceGenerators.splice(d,1)};this.applyForces=function(a){for(var b=this.entries.length;b--;)for(var c=this.entries[b],d=c.particle,c=c.forceGenerators,e=c.length;e--;)c[e].applyForce(d,a)};this.accept=function(a){for(var b=this.entries.length;b--;)for(var c=this.entries[b],d=c.particle,c=c.forceGenerators,e=c.length;e--;)c[e].accept(a,
d)}}function ParticleForceGenerator(){this.applyForce=function(){};this.accept=function(){};this.toString=function(){return this}}
function ParticleGravityForceGenerator(a){this.gravitation=a||math.v2.create([0,constants.DEFAULT_GRAVITATIONAL_CONSTANT]);this.applyForce=function(a){a.hasFiniteMass()?a.applyForce(math.v2.multScalar(this.gravitation,a.getMass())):EngineInstance.debug&&EngineInstance.verbose&&console.debug("Particle %o has zero mass",a)};this.accept=function(a,c){a.visitGravityForceGenerator(this,c)};this.toString=function(){return"Gravity: "+this.gravitation.toString()}}ParticleGravityForceGenerator.prototype=new ParticleForceGenerator;
function ParticleWindForceGenerator(a){this.direction=a||math.v2.create();this.applyForce=function(a){a.hasFiniteMass()?a.applyForce(math.v2.multScalar(this.direction,a.getMass())):EngineInstance.debug&&EngineInstance.verbose&&console.debug("Particle %o has zero mass, will not apply wind",a)};this.accept=function(a,c){a.visitWindForceGenerator(this,c)};this.toString=function(){return"Wind: "+this.direction.toString()}}ParticleWindForceGenerator.prototype=new ParticleForceGenerator;
function ParticleDragForceGenerator(a,b){this.k1=a||constants.DEFAULT_DRAG_VELOCITY_COEFF;this.k2=b||constants.DEFAULT_DRAG_VELOCITY_SQUARED_COEFF;this.applyForce=function(a,b){var e=this.calculateForce(a,b);a.applyForce(e)};this.calculateForce=function(a){var b=math.v2.getMagnitude(a.vel),b=this.k1*b+this.k2*b*b,a=math.v2.normalize(a.vel);math.v2.multScalarMutate(a,-b);return a};this.accept=function(a,b){a.visitDragForceGenerator(this,b)};this.toString=function(){return"Drag: k1="+this.k1+" ,k2="+
this.k2}}ParticleDragForceGenerator.prototype=new ParticleForceGenerator;function ParticleSpringForceGenerator(a,b,c){this.particleOther=a;this.springConstant=b;this.restLength=c;this.applyForce=function(a){var b=math.v2.create(a.pos);math.v2.subMutate(b,this.particleOther.pos);var c=math.v2.getMagnitude(b),c=Math.abs(c-this.restLength);c*=this.springConstant;math.v2.normalizeMutate(b);math.v2.multScalarMutate(b,-c);a.applyForce(b)};this.accept=function(a,b){a.visitSpringForceGenerator(this,b)}}
ParticleSpringForceGenerator.prototype=new ParticleForceGenerator;function ParticleAnchoredSpringForceGenerator(a,b,c){this.anchor=a;this.springConstant=b;this.restLength=c;this.applyForce=function(a){var b=math.v2.create(a.pos);math.v2.subMutate(b,this.anchor);var c=math.v2.getMagnitude(b),c=Math.abs(c-this.restLength);c*=this.springConstant;math.v2.normalizeMutate(b);math.v2.multScalarMutate(b,-c);a.applyForce(b)};this.accept=function(a,b){a.visitAnchoredSpringForceGenerator(this,b)}}
ParticleAnchoredSpringForceGenerator.prototype=new ParticleForceGenerator;
function ParticleBungeeForceGenerator(a,b,c){this.particleOther=a;this.springConstant=b;this.restLength=c;this.applyForce=function(a){var b=math.v2.create(a.pos);math.v2.subMutate(b,this.particleOther.pos);var c=math.v2.getMagnitude(b);c<=this.restLength||(c=this.springConstant*(c-this.restLength),math.v2.normalizeMutate(b),math.v2.multScalarMutate(b,-c),a.applyForce(b))};this.accept=function(a,b){a.visitBungeeForceGenerator(this,b)}}ParticleBungeeForceGenerator.prototype=new ParticleForceGenerator;
function ParticleAnchoredBungeeForceGenerator(a,b,c){this.anchor=a;this.springConstant=b;this.restLength=c;this.applyForce=function(a){var b=math.v2.create(a.pos);math.v2.subMutate(b,this.anchor);var c=math.v2.getMagnitude(b);c<=this.restLength||(c=this.springConstant*(c-this.restLength),math.v2.normalizeMutate(b),math.v2.multScalarMutate(b,-c),a.applyForce(b))};this.accept=function(a,b){a.visitAnchoredBungeeForceGenerator(this,b)}}ParticleAnchoredBungeeForceGenerator.prototype=new ParticleForceGenerator;
function ParticleBuoyancyForceGenerator(a,b,c,d){this.anchor=a;this.maxDepth=b;this.volume=c;this.liquidDensity=d||1E3;this.applyForce=function(a){var b=this.anchor[1]-a.pos[1];if(!(b<=-this.maxDepth)){var c=math.v2.create();b>this.maxDepth&&(c[1]=this.liquidDensity*this.volume,a.applyForce(c))}};this.accept=function(a,b){a.visitBuoyancyForceGenerator(this,b)}}ParticleBuoyancyForceGenerator.prototype=new ParticleForceGenerator;function ParticleForceGeneratorFactory(){}
ParticleForceGeneratorFactory.createGravity=function(a,b){a.add(b,new ParticleGravityForceGenerator)};ParticleForceGeneratorFactory.createWind=function(a,b,c){a.add(b,new ParticleWindForceGenerator(c))};ParticleForceGeneratorFactory.createDrag=function(a,b,c,d){a.add(b,new ParticleDragForceGenerator(c,d))};
ParticleForceGeneratorFactory.createSpring=function(a,b,c,d,e){var g=new ParticleSpringForceGenerator(c,d,e);a.add(b,g);c.addEventListener("die",function(){EngineInstance.debug&&console.debug("Removing force generator for dead particle %s",this.toString());a.removeForceGenerator(g)});var f=new ParticleSpringForceGenerator(b,d,e);a.add(c,f);b.addEventListener("die",function(){EngineInstance.debug&&console.debug("Removing force generator for dead particle %s",this.toString());a.removeForceGenerator(f)})};
ParticleForceGeneratorFactory.createAnchoredSpring=function(a,b,c,d,e){a.add(b,new ParticleAnchoredSpringForceGenerator(c,d,e))};
ParticleForceGeneratorFactory.createBungee=function(a,b,c,d,e){var g=new ParticleBungeeForceGenerator(c,d,e);a.add(b,g);c.addEventListener("die",function(){EngineInstance.debug&&console.debug("Removing bungee force generator for dead particle %s",this.toString());a.removeForceGenerator(g)});var f=new ParticleBungeeForceGenerator(b,d,e);a.add(c,f);b.addEventListener("die",function(){EngineInstance.getInstance().debug&&console.debug("Removing bungee force generator for dead particle %s",this.toString());
a.removeForceGenerator(f)})};ParticleForceGeneratorFactory.createAnchoredBungee=function(a,b,c,d,e){a.add(b,new ParticleAnchoredBungeeForceGenerator(c,d,e))};ParticleForceGeneratorFactory.createBuoyancy=function(a,b,c,d,e,g){a.add(b,new ParticleBuoyancyForceGenerator(c,d,e,g))};var CONTACT_TYPE={BOX:1,INTER:2,CABLE:4,CABLE_ANCHORED:8,ROD:16,ROD_ANCHORED:32};
function ParticleContact(){this.particles=[];this.restitution=0;this.contactNormal=math.v2.create();this.penetration=0;this.resolve=function(a){this.resolveVelocity(a);this.resolveInterpenetration(a)};this.calculateSeparatingVelocity=function(){var a=math.v2.create(this.particles[0].vel);this.particles[1]&&math.v2.subMutate(a,this.particles[1].vel);return math.v2.dotProduct(a,this.contactNormal)};this.resolveVelocity=function(a){var b=a/1E3,a=this.calculateSeparatingVelocity();if(!(a>0)){var c=-a*
this.restitution,d=math.v2.create(this.particles[0].acc);this.particles[1]&&math.v2.subMutate(d,this.particles[1].acc);b*=math.v2.dotProduct(d,this.contactNormal);b<0&&(c+=this.restitution*b,c<0&&(c=0));b=this.particles[0].inverseMass;this.particles[1]&&(b+=this.particles[1].inverseMass);b<=0||(a=math.v2.multScalar(this.contactNormal,(c-a)/b),math.v2.addMutate(this.particles[0].vel,math.v2.multScalar(a,this.particles[0].inverseMass)),this.particles[1]&&math.v2.addMutate(this.particles[1].vel,math.v2.multScalar(a,
-this.particles[1].inverseMass)))}};this.resolveInterpenetration=function(){if(!(this.penetration<=0)){var a=this.particles[0].inverseMass;this.particles[1]&&(a+=this.particles[1].inverseMass);a<=0||(a=math.v2.multScalar(this.contactNormal,-this.penetration/a),math.v2.addMutate(this.particles[0].pos,a.multScalar(this.particles[0].inverseMass)),this.particles[1]&&math.v2.addMutate(this.particles[1].pos,a.multScalar(this.particles[1].inverseMass)))}}}
function ParticleContactResolver(){this.maxIt=0;this.resolveContacts=function(a,b){for(var c=0;c<this.maxIt;){for(var d=0,e=a[0],g=a.length;g--;){var f=a[g],h=f.calculateSeparatingVelocity();h<d&&(d=h,e=f)}e.resolve(b);c++}}}function ParticleContactGenerator(){this.contactType=void 0;this.setContactType=function(a){this.contactType=a};this.addContact=function(){};this.accept=function(){}}
function ParticleLinkContactGenerator(){ParticleContactGenerator.call(this);this.particles=[];this.getCurrentLength=function(){return math.v2.getDistance(this.particles[0].pos,this.particles[1].pos)};this.addContact=function(){}}ParticleLinkContactGenerator.prototype=new ParticleContactGenerator;
function ParticleCableContactGenerator(a,b){ParticleLinkContactGenerator.call(this);this.setContactType(CONTACT_TYPE.CABLE);this.maxLength=a||0;this.restitution=b||0;this.addContact=function(a){var b=this.getCurrentLength();if(b<=this.maxLength)return 0;var e=new ParticleContact;e.particles[0]=this.particles[0];e.particles[1]=this.particles[1];var g=math.v2.sub(this.particles[1].pos,this.particles[0].pos);math.v2.normalizeMutate(g);e.contactNormal=g;e.penetration=this.maxLength-b;e.restitution=this.restitution;
a.push(e);return 1};this.accept=function(a){a.visitCableContactGenerator(this)}}ParticleCableContactGenerator.prototype=new ParticleLinkContactGenerator;
function ParticleAnchoredCableContactGenerator(a,b,c,d){ParticleContactGenerator.call(this);this.setContactType(CONTACT_TYPE.CABLE_ANCHORED);this.particle=a;this.anchor=b;this.maxLength=c||0;this.restitution=d||0;this.getCurrentLength=function(){var a=math.v2.sub(this.particle.pos,this.anchor);return math.v2.getMagnitude(a)};this.addContact=function(a){var b=this.getCurrentLength();if(b<=this.maxLength)return 0;var c=new ParticleContact;c.particles[0]=this.particle;var d=math.v2.sub(this.particle.pos,
this.anchor);math.v2.inverseMutate(d);math.v2.normalizeMutate(d);c.contactNormal=d;c.penetration=this.maxLength-b;c.restitution=this.restitution;a.push(c);return 1};this.accept=function(a){a.visitAnchoredCableContactGenerator(this)}}ParticleAnchoredCableContactGenerator.prototype=new ParticleContactGenerator;
function ParticleRodContactGenerator(a){ParticleLinkContactGenerator.call(this);this.setContactType(CONTACT_TYPE.ROD);this.length=a||0;this.addContact=function(a){var c=this.getCurrentLength();if(c==this.length)return 0;var d=new ParticleContact;d.particles[0]=this.particles[0];d.particles[1]=this.particles[1];var e=math.v2.sub(this.particles[1].pos,this.particles[0].pos);math.v2.normalizeMutate(e);c>this.length?(d.contactNormal=e,d.penetration=this.length-c):(d.contactNormal=math.v2.multScalar(e,
-1),d.penetration=c-this.length);d.restitution=0;a.push(d);return 1};this.accept=function(a){a.visitRodContactGenerator(this)}}ParticleRodContactGenerator.prototype=new ParticleLinkContactGenerator;
function ParticleAnchoredRodContactGenerator(a,b,c){ParticleContactGenerator.call(this);this.setContactType(CONTACT_TYPE.ROD_ANCHORED);this.particle=a;this.anchor=b;this.length=c||0;this.getCurrentLength=function(){return math.v2.getDistance(this.particle.pos,this.anchor)};this.addContact=function(a){var b=this.getCurrentLength(),c=new ParticleContact;c.particles[0]=this.particle;var f=math.v2.sub(this.particle.pos,this.anchor);math.v2.normalizeMutate(f);b>this.length?(c.contactNormal=math.v2.inverse(f),
c.penetration=this.length-b):(c.contactNormal=f,c.penetration=b-this.length);c.restitution=0;a.push(c);return 1};this.accept=function(a){a.visitAnchoredRodContactGenerator(this)}}ParticleAnchoredRodContactGenerator.prototype=new ParticleContactGenerator;
function ParticleCollisionContactGenerator(a){this.collisionRadius=a||5;this.setContactType(CONTACT_TYPE.INTER);this.particles=[];this.addContact=function(a,c){for(var d=0,e=this.particles.length;e--;){if(d>=c)break;for(var g=this.particles[e],f=this.particles.length;f--;)if(e!=f){var h=this.particles[f],k=math.v2.sub(g.pos,h.pos),l=math.v2.getMagnitude(k);if(l<this.collisionRadius){math.v2.normalizeMutate(k);var m=new ParticleContact;m.particles[0]=g;m.particles[1]=h;m.contactNormal=k;m.penetration=
l-this.collisionRadius;a.push(m);d++}}}return d};this.accept=function(a){a.visitCollisionContactGenerator(this)}}ParticleCollisionContactGenerator.prototype=new ParticleContactGenerator;
function ParticleBoxContactGenerator(a,b){this.setContactType(CONTACT_TYPE.BOX);this.box=a;this.collisionRadius=b||0;this.particles=[];this.addContact=function(b,d){for(var e=0,g=this.particles.length;g--;){if(e>=d)break;var f=this.particles[g];if(!a.shrink(this.collisionRadius).isPointInside(f.pos)){var h=math.v2.create(),k=0;f.pos[0]<this.box.x+this.collisionRadius&&(h[0]=1,h[1]=0,k=f.pos[0]-this.box.x-this.collisionRadius);f.pos[0]>this.box.x+this.box.width+this.collisionRadius&&(h[0]=-1,h[1]=
0,k=this.box.x+this.box.width+this.collisionRadius-f.pos[0]);f.pos[1]<this.box.y+this.collisionRadius&&(h[0]=0,h[1]=1,k=f.pos[1]-this.box.y-this.collisionRadius);f.pos[1]>this.box.y+this.box.height+this.collisionRadius&&(h[0]=0,h[1]=-1,k=this.box.y+this.box.height+this.collisionRadius-f.pos[1]);var l=new ParticleContact;l.particles[0]=f;l.contactNormal=h;l.penetration=k;l.restitution=constants.DEFAULT_COLLISION_RESTITUTION;b.push(l);e++}}return e};this.accept=function(a){a.visitBoxCollisionContactGenerator(this)}}
ParticleBoxContactGenerator.prototype=new ParticleContactGenerator;function ParticleContactGeneratorFactory(){}ParticleContactGeneratorFactory.createCollisionBox=function(a,b,c,d){c=new ParticleBoxContactGenerator(c,d);c.particles=b;a.addContactGenerator(c)};ParticleContactGeneratorFactory.createCollisionDetection=function(a,b,c){c=new ParticleCollisionContactGenerator(c);c.particles=b;a.addContactGenerator(c)};
ParticleContactGeneratorFactory.createCable=function(a,b,c,d,e){d=new ParticleCableContactGenerator(d,e);d.particles[0]=b;d.particles[1]=c;a.addContactGenerator(d)};ParticleContactGeneratorFactory.createAnchoredCable=function(a,b,c,d,e){c=new ParticleAnchoredCableContactGenerator(b,c,d,e);c.particle=b;a.addContactGenerator(c)};ParticleContactGeneratorFactory.createRod=function(a,b,c,d){d=new ParticleRodContactGenerator(d);d.particles[0]=b;d.particles[1]=c;a.addContactGenerator(d)};
ParticleContactGeneratorFactory.createAnchoredRod=function(a,b,c,d){c=new ParticleAnchoredRodContactGenerator(b,c,d);c.particle=b;a.addContactGenerator(c)};var PARTICLE_WORLD_GRAVITY=1,PARTICLE_WORLD_DRAG=2,PARTICLE_WORLD_WINDOW_COLLISION=4,PARTICLE_WORLD_CONTACT_EVENTS=8,PARTICLE_WORLD_ALL=PARTICLE_WORLD_GRAVITY|PARTICLE_WORLD_DRAG|PARTICLE_WORLD_WINDOW_COLLISION|PARTICLE_WORLD_CONTACT_EVENTS;function ContactEvent(a,b){this.contact=a;this.contactType=b}
function ParticleWorldVisitor(){this.visitWorld=function(){};this.visitParticle=function(){};this.visitGravityForceGenerator=function(){};this.visitWindForceGenerator=function(){};this.visitDragForceGenerator=function(){};this.visitSpringForceGenerator=function(){};this.visitAnchoredSpringForceGenerator=function(){};this.visitBungeeForceGenerator=function(){};this.visitAnchoredBungeeForceGenerator=function(){};this.visitBuoyancyForceGenerator=function(){};this.visitCableContactGenerator=function(){};
this.visitAnchoredCableContactGenerator=function(){};this.visitRodContactGenerator=function(){};this.visitAnchoredRodContactGenerator=function(){};this.visitCollisionContactGenerator=function(){};this.visitBoxCollisionContactGenerator=function(){}}
function ParticleWorld(a){Observable.call(this);this.contactEventsEnabled=!1;this.oncontact=void 0;this.contact=function(a){if(this.oncontact)this.oncontact(a);this.dispatchEvent("contact",a)};this.particles=[];this.forceRegistry=new ParticleForceRegistry;this.resolver=new ParticleContactResolver;this.contactGenerators=[];this.contacts=[];this.maxContacts=100;this.globalForceGenerators=[];this.flags=a||0;this.addContactGenerator=function(a){this.contactGenerators.push(a);a.particles&&(a.particles[0]&&
a.particles[0].addEventListener("die",function(){particleWorld.removeContactGenerator(a)}),a.particles[1]&&a.particles[1].addEventListener("die",function(){particleWorld.removeContactGenerator(a)}))};this.removeContactGenerator=function(a){for(var c=this.contactGenerators.length;c--;)this.contactGenerators[c]===a&&this.contactGenerators.splice(c,1)};this.addParticle=function(a){return this.particles.push(a)};this.removeParticle=function(a){for(var c=void 0,d=this.particles.length;d--;)if(this.particles[d]===
a){EngineInstance.debug&&console.debug("Removing particle %s",a.toString());c=this.particles.splice(d,1);a.die();this.forceRegistry.removeForceGenerators(a);EngineInstance.debug&&console.debug("Removing particle %d",d);break}return c};this.getFirstParticleWithinWorld=function(a,c){for(var d=this.particles.length;d--;){var e=this.particles[d];if(e.isCloseToPoint(a,c))return e}};this.getFirstParticleWithinWindow=function(a,c){for(var d=this.particles.length;d--;){var e=this.particles[d];if(math.v2.isWithin(window(e.pos),
a,c))return e}};this.update=function(a){this.startFrame();this.runPhysics(a)};this.startFrame=function(){for(var a=this.particles.length;a--;)this.particles[a].clearForceAccum()};this.generateContacts=function(){for(var a=this.maxContacts,c=this.contactGenerators.length;c--;){var d=this.contactGenerators[c],e=d.addContact(this.contacts,a);if(this.contactEventsEnabled&&e>0)for(c=0;c<e;c++)this.contact(new ContactEvent(this.contacts[this.contacts.length-c],d.contactType));a-=e;if(a<=0)break}return this.maxContacts-
a};this.integrate=function(a){for(var c=this.particles.length;c--;)this.particles[c].integrate(a)};this.runPhysics=function(a){this.applyGlobalForces(a);this.forceRegistry.applyForces(a);this.integrate(a);this.resolver.maxIt=this.generateContacts()*2;this.resolver.resolveContacts(this.contacts,a);this.contacts=[]};this.addGlobalForce=function(a){this.globalForceGenerators.push(a)};this.applyGlobalForces=function(a){for(var c=this.globalForceGenerators.length;c--;)for(var d=this.globalForceGenerators[c],
e=this.particles.length;e--;)d.applyForce(this.particles[e],a)};this.addGlobalGravityForce=function(a){this.addGlobalForce(new ParticleGravityForceGenerator(a))};this.addGlobalDragForce=function(a,c){this.addGlobalForce(new ParticleDragForceGenerator(a,c))};this.addWindowCollisionBox=function(){ParticleContactGeneratorFactory.createCollisionBox(this,this.particles,EngineInstance.windowRect)};this.flags&PARTICLE_WORLD_GRAVITY&&(this.addGlobalGravityForce(),EngineInstance.debug&&console.debug("Added global gravity force"));
this.flags&PARTICLE_WORLD_DRAG&&(this.addGlobalDragForce(),EngineInstance.debug&&console.debug("Added global drag force"));this.flags&PARTICLE_WORLD_WINDOW_COLLISION&&(this.addWindowCollisionBox(),EngineInstance.debug&&console.debug("Added window collision box"));if(this.flags&PARTICLE_WORLD_CONTACT_EVENTS)this.contactEventsEnabled=!0,EngineInstance.debug&&console.debug("Contact events enabled");this.accept=function(a){a.visitWorld(this);for(var c=this.globalForceGenerators.length;c--;)for(var d=
this.globalForceGenerators[c],e=this.particles.length;e--;){var g=this.particles[e];d.accept(a,g)}for(c=this.contactGenerators.length;c--;)this.contactGenerators[c].accept(a);this.forceRegistry.accept(a);for(e=this.particles.length;e--;)g=this.particles[e],g.accept(a)}}ParticleWorld.prototype=new Observable;function RigidBody(a,b){Observable.call(this);this.uid=RigidBody.getNextUid();this.orientation=new Vector2(1,0);this.angVel=0;this.pos=new Vector2;this.vel=new Vector2;this.acc=new Vector2;this.angularDamping=this.damping=1;this.inverseMass=0;if(a)this.inverseMass=1/a;this.inverseInertia=0;if(b)this.inverseInertia=1/b;this.forceAccum=new Vector2;this.torqueAccum=0;this.transformMatrix=void 0;this.calculateDerivedData=function(){this.calculateTransformMatrix()};this.calculateTransformMatrix=function(){this.transformMatrix=
new TransformationMatrix3(this.getOrientationAngle(),this.pos.x,this.pos.y)};this.setOrientationAngle=function(a){this.orientation.x=Math.cos(a);this.orientation.y=Math.sin(a);this.orientation.normalizeMutate()};this.setOrientation=function(a){this.orientation=a};this.getOrientationAngle=function(){return Math.atan2(this.orientation.y,this.orientation.x)};this.getOrientation=function(){return this.orientation};this.getPointInWorldSpace=function(a){a=new Vector3(a.x,a.y,1);a=this.transformMatrix.multVector(a);
return new Vector2(a.x,a.y)};this.getPointInLocalSpace=function(a){a=new Vector3(a.x,a.y,1);a=this.transformMatrix.getInverse().multVector(a);return new Vector2(a.x,a.y)};this.hasFiniteMass=function(){return this.inverseMass>0};this.applyForce=function(a){this.forceAccum.addMutate(a)};this.applyForceAtBodyPoint=function(a,b){var e=this.getPointInWorldSpace(b);this.addForceAtPoint(a,e)};this.addForceAtPoint=function(a,b){this.applyForce(a);var e=b.clone();e.subMutate(this.pos);this.applyTorque(e.vectorProduct(a))};
this.clearForceAccum=function(){this.forceAccum.zeroMutate()};this.applyTorque=function(a){this.torqueAccum+=a};this.clearTorqueAccum=function(){this.torqueAccum=0};this.clearAccums=function(){this.clearForceAccum();this.clearTorqueAccum()};this.setInverseMass=function(a){this.inverseMass=a};this.setMass=function(a){this.inverseMass=a==0?0:1/a};this.getMass=function(){return this.inverseMass==0?0:1/this.inverseMass};this.setInverseInertia=function(a){this.inverseInertia=a};this.setInertia=function(a){this.inverseInertia=
a==0?0:1/a};this.getInertia=function(){return this.inverseInertia==0?0:1/this.inverseInertia};this.integrate=function(a){a/=1E3;this.pos.addMutate(this.vel.multScalar(a));this.vel.addMutate(this.acc.add(this.forceAccum.multScalar(this.inverseMass)).multScalar(a));this.vel.multScalarMutate(Math.pow(this.damping,a));this.setOrientationAngle(this.getOrientationAngle()+this.angVel*a);this.angVel+=this.torqueAccum*this.inverseInertia*a;this.angVel*=Math.pow(this.angularDamping,a);this.calculateDerivedData();
this.clearAccums()};this.accept=function(a){a.visitRigidBody(this)};this.ondie=void 0;this.die=function(){if(this.ondie)this.ondie();this.dispatchEvent("die")};this.toString=function(){return"uid="+this.uid}}RigidBody.prototype=new Observable;RigidBody.nextUid=0;RigidBody.getNextUid=function(){return RigidBody.nextUid++};function ForceGenerator(){this.applyForce=function(){};this.accept=function(){};this.toString=function(){return this}}
function GravityForceGenerator(a){this.gravitation=a||new Vector2(0,constants.DEFAULT_GRAVITATIONAL_CONSTANT);this.applyForce=function(a){a.hasFiniteMass()?a.applyForce(this.gravitation.multScalar(a.getMass())):debug&&verbose&&console.debug("RigidBody %o has zero mass",a)};this.accept=function(a,c){a.visitGravityForceGenerator(this,c)};this.toString=function(){return"Gravity: "+this.gravitation.toString()}}GravityForceGenerator.prototype=new ForceGenerator;
function SpringForceGenerator(a,b,c,d,e){this.connectionPoint=a;this.connectionPointOther=c;this.rigidBodyOther=b;this.springConstant=d;this.restLength=e;this.applyForce=function(a){var b=a.getPointInWorldSpace(this.connectionPoint),c=this.rigidBodyOther.getPointInWorldSpace(this.connectionPointOther),c=b.sub(c),d=c.getMagnitude(),d=Math.abs(d-this.restLength);d*=this.springConstant;c.normalizeMutate();c.multScalarMutate(-d);a.addForceAtPoint(c,b)};this.accept=function(a,b){a.visitSpringForceGenerator(this,
b)}}SpringForceGenerator.prototype=new ForceGenerator;function ConstantTorqueForceGenerator(a){this.torque=a||0;this.applyForce=function(a){a.hasFiniteMass()?a.applyTorque(this.torque):debug&&verbose&&console.debug("RigidBody %o has zero mass",a)};this.toString=function(){return"Constant Torque: "+this.torque}}ConstantTorqueForceGenerator.prototype=new ForceGenerator;
function AeroForceGenerator(a,b,c){this.tensor=a;this.position=b;this.windspeed=c||new Vector2(0,0);this.toString=function(){return"Aero: windspeed="+this.windspeed.toString()+", tensor="+a.toString()+", pos="+pos.toString()}}AeroForceGenerator.prototype=new ForceGenerator;
function AeroControlForceGenerator(a,b,c,d,e){AeroForceGenerator.call(this,a,d,e);this.minTensor=b;this.maxTensor=c;this.controlSetting=0;this.getTensor=function(){return this.controlSetting==-1?this.minTensor:this.controlSetting==1?this.maxTensor:this.tensor};this.applyForce=function(a){if(a.hasFiniteMass()){var b=this.getTensor().multVector(this.windspeed);a.applyForceAtBodyPoint(b,this.position)}else debug&&verbose&&console.debug("RigidBody %o has zero mass",a)};this.accept=function(a,b){a.visitAeroControlForceGenerator(this,
b)};this.toString=function(){return"Aero: windspeed="+this.windspeed.toString()+", tensor="+tensor.toString()+", pos="+pos.toString()}}AeroControlForceGenerator.prototype=new AeroForceGenerator;function ForceGeneratorFactory(){}ForceGeneratorFactory.createGravity=function(a,b,c){a.add(b,new GravityForceGenerator(c))};ForceGeneratorFactory.createConstantTorque=function(a,b,c){a.add(b,new ConstantTorqueForceGenerator(c))};
ForceGeneratorFactory.createSpring=function(a,b,c,d,e,g,f){var h=new SpringForceGenerator(c,d,e,g,f);a.add(b,h);b.addEventListener("die",function(){debug&&console.debug("Removing force generator for dead rigid body %s",this.toString());a.removeForceGenerator(h)});var k=new SpringForceGenerator(e,b,c,g,f);a.add(d,k);d.addEventListener("die",function(){debug&&console.debug("Removing force generator for dead rigid body %s",this.toString());a.removeForceGenerator(k)})};
function ForceRegistry(){this.entries=[];this.add=function(a,b){var c,d=!1;for(i in this.entries)if(c=this.entries[i],c.rigidBody===a){d=!0;break}d?c.forceGenerators.push(b):(c={rigidBody:a,forceGenerators:Array(b)},this.entries.push(c))};this.getForceGenerators=function(a){for(i in this.entries){var b=this.entries[i];if(b.rigidBody===a)return b.forceGenerators}};this.removeForceGenerators=function(a){for(i in this.entries)this.entries[i].rigidBody===a&&this.rigidBodies.splice(i,1)};this.removeForceGenerator=
function(a){for(i in this.entries){var b=this.entries[i];for(j in b.forceGenerators)b.forceGenerators[j]===a&&b.forceGenerators.splice(j,1)}};this.applyForces=function(a){for(i in this.entries){var b=this.entries[i],c=b.rigidBody,b=b.forceGenerators;for(j in b)b[j].applyForce(c,a)}};this.accept=function(a){for(i in this.entries){var b=this.entries[i],c=b.rigidBody,b=b.forceGenerators;for(j in b)b[j].accept(a,c)}}}
function Contact(){this.ridigBodies=[];this.contactNormal=this.contactPoint=void 0;this.penetration=0;this.resolve=function(a){this.resolveVelocity(a);this.resolveInterpenetration(a)};this.calculateSeparatingVelocity=function(){var a=this.particles[0].vel.clone();this.particles[1]&&a.subMutate(this.particles[1].vel);return a.dotProduct(this.contactNormal)};this.resolveVelocity=function(a){var b=a/1E3,a=this.calculateSeparatingVelocity();if(!(a>0)){var c=-a*this.restitution,d=this.particles[0].acc.clone();
this.particles[1]&&d.subMutate(this.particles[1].acc);b*=d.dotProduct(this.contactNormal);b<0&&(c+=resitution*b,c<0&&(c=0));b=this.particles[0].inverseMass;this.particles[1]&&(b+=this.particles[1].inverseMass);b<=0||(a=this.contactNormal.multScalar((c-a)/b),this.particles[0].vel.addMutate(a.multScalar(this.particles[0].inverseMass)),this.particles[1]&&this.particles[1].vel.addMutate(a.multScalar(-this.particles[1].inverseMass)))}};this.resolveInterpenetration=function(){if(!(this.penetration<=0)){var a=
this.particles[0].inverseMass;this.particles[1]&&(a+=this.particles[1].inverseMass);a<=0||(a=this.contactNormal.multScalar(-this.penetration/a),this.particles[0].pos.addMutate(a.multScalar(this.particles[0].inverseMass)),this.particles[1]&&this.particles[1].pos.addMutate(a.multScalar(this.particles[1].inverseMass)))}}}function BoundingVolume(){}
function BoundingSphere(a,b){BoundingVolume.call(this);this.center=a||void 0;this.radius=b||0;this.overlaps=function(a){return Vector2.isWithin(this.center,a.center,this.radius+a.radius)}}BoundingSphere.prototype=new BoundingVolume;BoundingSphere.enclose=function(a,b){var c=new BoundingSphere,d=a.center.add(b.center);d.multScalar(0.5);c.center=d;c.radius=a.radius+b.radius;return c};function BoundingBox(a,b){BoundingVolume.call(this);this.center=a||void 0;this.halfSize=b||void 0}
BoundingBox.prototype=new BoundingVolume;function PotentialContact(a){this.center=a||void 0}
function BVHNode(a,b,c){this.children=a||void 0;this.volume=b||void 0;this.rigidBody=c||void 0;this.isLeaf=function(){return this.rigidBody!=void 0};this.insert=function(a,b){this.isLeaf()?(this.children[0]=new BVHNode(this,this.volume,this.rigidBody),this.children[1]=new BVHNode(this,b,a),this.rigidBody=void 0,this.recalculateBoundingVolume()):this.children[0].volume.getGrowth(b)<this.children[1].volume.getGrowth(b)?this.children[0].insert(a,b):this.children[1].insert(a,b)};this.remove=function(){if(this.parent){var a=
void 0,a=this.parent.children[0]===this?this.parent.children[1]:this.parent.children[0];this.parent.volume=a.volume;this.parent.rigidBody=a.rigidBody;this.parent.children[0]=a.children[0];this.parent.children[1]=a.children[1];a.parent=void 0;a.rigidBody=void 0;a.children[0]=void 0;a.children[1]=void 0;a.remove();this.parent.recalculateBoundingVolume()}if(this.children[0])this.children[0].parent=void 0,this.children[0].remove();if(this.children[1])this.children[1].parent=void 0,this.children[1].remove()};
this.getPotentialContacts=function(a,b){if(this.isLeaf()||b==0)return 0;return this.children[0].getPotentialContactsWith(this.children[1],a,b)};this.getPotentialContactsWith=function(a,b,c){if(!this.overlaps(a)||c==0)return 0;if(this.isLeaf()&&a.isLeaf())return a=new PotentialContact([this.rigidBody,a.rigidBody]),b.push(a),1;if(a.isLeaf()||!this.isLeaf()&&this.volume.getSize()>=a.volume.getSize()){var f=this.children[0].getPotentialContactsWith(a,b,c);return c>f?f+this.children[1].getPotentialContactsWith(a,
b,c):f}else return f=a.children[0].getPotentialContactsWith(a,b,c),c>f?f+a.children[1].getPotentialContactsWith(a,b,c):f};this.overlaps=function(a){return this.volume.overlaps(a.volume)}}function Plane2(a,b){this.position=a||void 0;this.direction=b||void 0}BSP_CHILD_TYPE={BSP_CHILD_NODE:1,BSP_CHILD_OBJECTS:2};function BSPChild2(a){this.type=a||void 0;this.objects=this.node=void 0}function BSPNode2(a,b,c){this.plane=a||void 0;this.front=b||void 0;this.back=c||void 0}
function QuadNodeTree2(a){this.position=a||void 0;this.children=[];this.getChildIndex=function(a){var c=0;a.x>this.position.x&&(c+=1);a.y>this.position.y&&(c+=2);return c}}function Grid2(a,b,c){this.xExtent=a||0;this.yExtent=b||0;this.locations=[];this.origin=c||void 0;this.oneOverCellSize=void 0;this.getLocationIndex=function(a){a=a.multScalar(this.oneOverCellSize);return a.x+this.xExtent*a.y}}function CollisionPrimitive2(a,b){this.rigidBody=a||void 0;this.offset=b||void 0}
function CollisionCircle(a,b,c){CollisionPrimitive2.call(this,a,b,c);this.radius=c||0}CollisionCircle.prototype=new CollisionPrimitive2;
function CollisionDetector2(){this.circleAndCircle=function(a,b,c){var d=a.rigidBody.pos,e=d.sub(b.rigidBody.pos),g=e.getMagnitude();if(g<=0||g>=a.radius+b.radius)return 0;var f=e.multScalar(1/g),h=new Contact;h.contactNormal=f;h.contactPoint=d.add(e.multScalar(0.5));h.penetration=a.radius+b.radius-g;h.ridigBodies[0]=a.rigidBody;h.ridigBodies[1]=b.rigidBody;c.push(h);return 1}}
function WorldVisitor(){this.visitWorld=function(){};this.visitRigidBody=function(){};this.visitGravityForceGenerator=function(){};this.visitSpringForceGenerator=function(){};this.visitAeroControlForceGenerator=function(){}}
function World(){this.rigidBodies=[];this.forceRegistry=new ForceRegistry;this.globalForceGenerators=[];this.addRigidBody=function(a){return this.rigidBodies.push(a)};this.removeParticle=function(a){var b=void 0;for(i in this.rigidBodies)if(this.rigidBodies[i]===a){debug&&console.debug("Removing rigid body %s",a.toString());b=this.rigidBodies.splice(i,1);b.die();break}return b};this.update=function(a){this.startFrame();this.runPhysics(a)};this.startFrame=function(){for(i in this.rigidBodies){var a=
this.rigidBodies[i];a.clearForceAccum();a.calculateDerivedData()}};this.integrate=function(a){for(i in this.rigidBodies)this.rigidBodies[i].integrate(a)};this.runPhysics=function(a){this.applyGlobalForces(a);this.forceRegistry.applyForces(a);this.integrate(a)};this.addGlobalForce=function(a){this.globalForceGenerators.push(a)};this.applyGlobalForces=function(a){for(j in this.globalForceGenerators){var b=this.globalForceGenerators[j];for(i in this.rigidBodies)b.applyForce(this.rigidBodies[i],a)}};
this.addGlobalGravityForce=function(a){this.addGlobalForce(new GravityForceGenerator(a))};this.accept=function(a){a.visitWorld(this);for(i in this.rigidBodies){var b=this.rigidBodies[i];b.accept(a);for(j in this.globalForceGenerators)this.globalForceGenerators[j].accept(a,b)}this.forceRegistry.accept(a)}};function Renderer(){this.renderParticleWorld=function(a){a.accept(ParticleWorldRenderVisitor.instance)};this.renderWorld=function(a){a.accept(WorldRenderVisitor.instance)}}Renderer.instance=new Renderer;
function ParticleWorldRenderVisitor(a){ParticleWorldVisitor.call(this);this.particleWorld=void 0;this.isPointInScreen=function(a){return a[0]>=0&&a[0]<EngineInstance.windowRect.width&&a[1]>=0&&a[1]<EngineInstance.windowRect.height};this.visitWorld=function(){this.particleWorld=particleWorld};this.visitParticle=function(b){b=window(b.pos);if(this.isPointInScreen(b))a.save(),a.fillStyle=constants.PARTICLE_COLOR,a.translate(b[0],b[1]),b=constants.PARTICLE_WIDTH,a.fillRect(-b,-b,b*2,b*2),a.restore()};
this.visitGravityForceGenerator=function(b,c){var d=window(c.pos),e=math.v2.multScalar(b.gravitation,c.getMass()),e=windowVector(e);if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.GRAVITY_COLOR,a.beginPath(),a.translate(d[0],d[1]),a.moveTo(0,0),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitWindForceGenerator=function(b,c){var d=window(c.pos),e=math.v2.multScalar(b.direction,c.getMass());if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=
constants.WIND_COLOR,a.beginPath(),a.translate(d[0],d[1]),a.moveTo(0,0),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitDragForceGenerator=function(b,c){var d=window(c.pos),e=b.calculateForce(c),e=windowVector(e);if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.DRAG_COLOR,a.beginPath(),a.translate(d[0],d[1]),a.moveTo(0,0),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitSpringForceGenerator=function(b,c){var d=window(c.pos),e=window(b.particleOther.pos);
if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.SPRING_COLOR,a.beginPath(),a.moveTo(d[0],d[1]),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitAnchoredSpringForceGenerator=function(b,c){var d=window(c.pos),e=window(b.anchor);if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.ANCHORED_SPRING_COLOR,a.beginPath(),a.moveTo(d[0],d[1]),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitBungeeForceGenerator=function(b,c){var d=
window(c.pos),e=window(b.particleOther.pos);if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.BUNGEE_COLOR,a.beginPath(),a.moveTo(d[0],d[1]),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitAnchoredBungeeForceGenerator=function(b,c){var d=window(c.pos),e=window(b.anchor);if(this.isPointInScreen(d)||this.isPointInScreen(e))a.save(),a.strokeStyle=constants.ANCHORED_BUNGEE_COLOR,a.beginPath(),a.moveTo(d[0],d[1]),a.lineTo(e[0],e[1]),a.stroke(),a.restore()};this.visitCableContactGenerator=
function(b){var c=window(b.particles[0].pos),b=window(b.particles[1].pos);if(this.isPointInScreen(c)||this.isPointInScreen(b))a.save(),a.strokeStyle=constants.CABLE_COLOR,a.beginPath(),a.moveTo(c[0],c[1]),a.lineTo(b[0],b[1]),a.stroke(),a.restore()};this.visitAnchoredCableContactGenerator=function(b){var c=window(b.particle.pos),b=window(b.anchor);if(this.isPointInScreen(c)||this.isPointInScreen(b))a.save(),a.strokeStyle=constants.ANCHORED_CABLE_COLOR,a.beginPath(),a.moveTo(c[0],c[1]),a.lineTo(b[0],
b[1]),a.stroke(),a.restore()};this.visitRodContactGenerator=function(b){var c=window(b.particles[0].pos),b=window(b.particles[1].pos);if(this.isPointInScreen(c)||this.isPointInScreen(b))a.save(),a.strokeStyle=constants.ROD_COLOR,a.beginPath(),a.moveTo(c[0],c[1]),a.lineTo(b[0],b[1]),a.stroke(),a.restore()};this.visitAnchoredRodContactGenerator=function(b){var c=window(b.particle.pos),b=window(b.anchor);if(this.isPointInScreen(c)||this.isPointInScreen(b))a.save(),a.strokeStyle=constants.ANCHORED_ROD_COLOR,
a.beginPath(),a.moveTo(c[0],c[1]),a.lineTo(b[0],b[1]),a.stroke(),a.restore()};this.visitCollisionContactGenerator=function(b){a.save();a.strokeStyle=constants.COLLISION_DETECTION_COLOR;for(i in b.particles){var c=window(b.particles[i].pos);this.isPointInScreen(c)&&(a.beginPath(),a.arc(c[0],c[1],b.collisionRadius,0,constants.TWO_PI),a.stroke())}a.restore()};this.visitBoxCollisionContactGenerator=function(b){a.save();a.strokeStyle=constants.COLLISION_BOX_COLOR;a.strokeRect(b.box[0],b.box[1],b.box.width,
b.box.height);a.strokeStyle=constants.COLLISION_BOX_TOL_COLOR;a.strokeRect(b.box[0]+b.collisionRadius,b.box[1]+b.collisionRadius,b.box.width-b.collisionRadius*2,b.box.height-b.collisionRadius*2);a.restore()}}ParticleWorldRenderVisitor.prototype=new ParticleWorldVisitor;ParticleWorldRenderVisitor.instance=new ParticleWorldRenderVisitor;
function WorldRenderVisitor(){WorldVisitor.call(this);this.rigidBodyWorld=void 0;this.visitWorld=function(a){this.rigidBodyWorld=a};this.visitRigidBody=function(a){a=window(a.pos);ctx.save();ctx.fillStyle=constants.PARTICLE_COLOR;ctx.translate(a[0],a[1]);a=constants.PARTICLE_WIDTH;ctx.fillRect(-a,-a,a*2,a*2);ctx.restore()};this.visitGravityForceGenerator=function(a,b){var c=window(b.pos);ctx.save();ctx.strokeStyle=constants.GRAVITY_COLOR;ctx.beginPath();ctx.translate(c[0],c[1]);ctx.moveTo(0,0);c=
math.v2.multScalar(a.gravitation,b.getMass());c=windowVector(c);ctx.lineTo(c[0],c[1]);ctx.stroke();ctx.restore()};this.visitSpringForceGenerator=function(a,b){var c=window(b.getPointInWorldSpace(a.connectionPoint)),d=window(a.rigidBodyOther.getPointInWorldSpace(a.connectionPointOther));ctx.save();ctx.strokeStyle=constants.SPRING_COLOR;ctx.beginPath();ctx.moveTo(c[0],c[1]);ctx.lineTo(d[0],d[1]);ctx.stroke();ctx.restore()};this.visitAeroControlForceGenerator=function(a,b){var c=window(b.getPointInWorldSpace(a.position)),
d=a.getTensor().multVector(a.windspeed);ctx.save();ctx.strokeStyle=constants.AERO_COLOR;ctx.beginPath();ctx.translate(c[0],c[1]);ctx.moveTo(0,0);c=windowVector(d);ctx.lineTo(c[0],c[1]);ctx.stroke();ctx.restore()}}WorldRenderVisitor.prototype=new WorldVisitor;WorldRenderVisitor.instance=new WorldRenderVisitor;
